routes/web.php
<?php
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\AccountController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\InternshipController;
use App\Http\Controllers\Admin\ResultController as AdminResultController;
use App\Http\Controllers\Admin\FormulaController;
use App\Http\Controllers\Admin\AlternativeController;
use App\Http\Controllers\Admin\CriteriaController;
use App\Http\Controllers\Admin\CriteriaValueController;
use App\Http\Controllers\Admin\SubCriteriaController;
use App\Http\Controllers\Admin\SubCriteriaValueController;

use App\Http\Controllers\User\InternshipVacancyController;
use App\Http\Controllers\User\ResultController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('account', AccountController::class);
    Route::resource('users', UserController::class);
    Route::resource('formulas', FormulaController::class);
    Route::resource('internships', InternshipController::class);
    Route::resource('internships.results', AdminResultController::class);
    Route::post('internships/{internship}/results', [AdminResultController::class, 'changeStatus'])->name('internships.results.changeStatus');
    Route::post('internships/{internship}/announce', [AdminResultController::class, 'announce'])->name('internships.results.announce');

    Route::resource('formulas.criterias', CriteriaController::class)->shallow();
    Route::resource('formulas.criteria-values', CriteriaValueController::class)->shallow();
    Route::resource('formulas.criterias.sub-criterias', SubCriteriaController::class)->shallow();
    Route::resource('formulas.criterias.sub-criteria-values', SubCriteriaValueController::class)->shallow();
    Route::resource('alternatives', AlternativeController::class);
    Route::resource('alternative-values', AlternativeValueController::class);

    Route::get('internship-vacancies/{internshipVacancy}/register', [InternshipVacancyController::class, 'registerForm'])->name('internship-vacancies.register');
    Route::post('internship-vacancies/{internshipVacancy}/register', [InternshipVacancyController::class, 'register'])->name('internship-vacancies.register.store');
    Route::resource('internship-vacancies', InternshipVacancyController::class);
    Route::resource('results', ResultController::class);
});

app/Models/Internship.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Internship extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'name',
        'description',
        'start_at',
        'end_at',
        'announce_at',
        'formula_id',
        'created_at',
        'updated_at'
    ];

    public function registrants()
    {
        return $this->hasMany('App\Models\Alternative', 'internship_id', 'id');
    }

    public function hasRegister()
    {
        return $this->hasOne('App\Models\Alternative', 'internship_id', 'id')
            ->where('user_id', auth()->user()->id);
    }

    public function formula()
    {
        return $this->belongsTo('App\Models\Formula', 'formula_id', 'id');
    }
}

app/Http/Controllers/Admin/InternshipController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Internship;
use App\Models\Formula;
use Illuminate\Http\Request;

class InternshipController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Internship::withCount('registrants')->latest()->get();

        return view('admin.internship.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $formulas = Formula::get();
        return view('admin.internship.create', compact('formulas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->validate([
            'name' => 'required|string',
            'formula_id' => 'required|exists:formulas,id',
            'description' => 'required|string'
        ]);

        Internship::create($input);

        return redirect()->route('internships.index')->with('success', 'Berhasil menambah data magang');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Internship  $internship
     * @return \Illuminate\Http\Response
     */
    public function show(Internship $internship)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Internship  $internship
     * @return \Illuminate\Http\Response
     */
    public function edit(Internship $internship)
    {
        $formulas = Formula::get();
        return view('admin.internship.edit', compact('formulas', 'internship'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Internship  $internship
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Internship $internship)
    {
        if($request->has('status')){
            if($request->status == 'start'){
                $internship->start_at = now();
                $internship->save();
                return redirect()->route('internships.index')->with('success', 'Berhasil membuka magang');
            }elseif($internship->start_at){
                $internship->end_at = now();
                $internship->save();
                return redirect()->route('internships.index')->with('success', 'Berhasil mengakhiri magang');
            }
        }else{
            $input = $request->validate([
                'name' => 'required|string',
                'formula_id' => 'required|exists:formulas,id',
                'description' => 'required|string'
            ]);
            $internship->update($input);
        }

        return redirect()->route('internships.index')->with('success', 'Berhasil mengubah data magang');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Internship  $internship
     * @return \Illuminate\Http\Response
     */
    public function destroy(Internship $internship)
    {
        //
    }
}

resources/views/admin/internship/create.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">TAMBAH DATA MAGANG</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Tambah Data Magang</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('internships.store') }}">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama/ Judul Magang</label>
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}" id="1">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Formula</label>
                        <select name="formula_id" class="form-control">
                            <option value="">Pilih Formula</option>
                            @foreach ($formulas as $item)
                                <option @if(old('formula_id') == $item->id) selected @endif value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Deskripsi</label>
                        <textarea name="description" id="editor">
                            {{ old('description') }}
                        </textarea>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
<script src="https://cdn.ckeditor.com/ckeditor5/29.0.0/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>
@endsection

resources/views/admin/internship/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">EDIT DATA MAGANG</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Edit Data Magang</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('internships.update', $internship->id) }}">
                @csrf
                @method('PATCH')
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama/ Judul Magang</label>
                        <input type="text" class="form-control" name="name" value="{{ old('name', $internship->name) }}" id="1">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Formula</label>
                        <select @if ($internship->announce_at)
                            disabled
                        @endif name="formula_id" class="form-control">
                            <option value="">Pilih Formula</option>
                            @foreach ($formulas as $item)
                                <option @if(old('formula_id', $internship->formula_id) == $item->id) selected @endif value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                        @if ($internship->announce_at)
                        <small id="emailHelp" class="form-text text-muted">Tidak bisa diubah karena data sudah diumumkan</small>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Deskripsi</label>
                        <textarea name="description" id="editor">
                            {{ old('description', $internship->description) }}
                        </textarea>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
<script src="https://cdn.ckeditor.com/ckeditor5/29.0.0/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>
@endsection

resources/views/admin/internship/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h2 class="m-0 text-dark">DATA LOWONGAN MAGANG</h2>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">User</li>
            </ol>
        </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="10">NO</th>
                        <th>JUDUL</th>
                        <th>FORMULA</th>
                        <th>PENDAFTAR</th>
                        <th>STATUS</th>
                        <th width="300">AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data as $sis)
                    <tr>
                        <td class="text-center">{{$loop->iteration}}</td>
                        <td>{{$sis->name}}</td>
                        <td>{{$sis->formula->name}}</td>
                        <td>{{$sis->registrants_count}}</td>
                        <td>
                            @if (!$sis->start_at)
                             <span class="badge badge-danger">BELUM DIBUKA</span> 
                            @elseif(!$sis->end_at)
                             <span class="badge badge-warning">DIBUKA</span> 
                            @elseif(!$sis->announce_at)
                             <span class="badge badge-info">BELUM DIUMUMKAN</span> 
                            @else
                             <span class="badge badge-success">SELESAI</span> 
                            @endif
                        </td>
                        <td class="text-center">
                            @if(!$sis->start_at)
                            <form id="edit-{{$sis->id}}" action="{{ route('internships.update', $sis->id) }}" method="post" style="display: inline;">
                                @method('PATCH')
                                @csrf
                                <input type="hidden" name="status" value="start">
                                <button onClick="return confirm('Apakah Anda yakin ingin membuka lowongan ini?')" class="btn btn-success"><i class="fa fa-check"></i>Mulai</button>
                            </form>
                            @elseif(!$sis->end_at)
                            <form id="edit-{{$sis->id}}" action="{{ route('internships.update', $sis->id) }}" method="post" style="display: inline;">
                                @method('PATCH')
                                @csrf
                                <input type="hidden" name="status" value="end">
                                <button onClick="return confirm('Apakah Anda yakin ingin mengakhiri lowongan ini?')" class="btn btn-warning"><i class="fa fa-times"></i>Akhiri</button>
                            </form>
                            @else
                            <a href="{{ route('internships.results.index', $sis->id) }}">
                                <button class="btn btn-info">Lihat Hasil</button>
                            </a>
                            @endif
                            <a href="{{ route('internships.edit', $sis->id) }}">
                                <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil"></i></button>
                            </a>
                            <form id="delete-siseria-{{$sis->id}}" action="{{ route('internships.destroy', $sis->id) }}" method="post" style="display: inline;">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    $("#data-admin_length").append('<a  href="{{ route('internships.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
});
</script>
@endsection