routes/web.php
<?php
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\AccountController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\InternshipController;
use App\Http\Controllers\Admin\ResultController as AdminResultController;
use App\Http\Controllers\Admin\FormulaController;
use App\Http\Controllers\Admin\AlternativeController;
use App\Http\Controllers\Admin\CriteriaController;
use App\Http\Controllers\Admin\CriteriaValueController;
use App\Http\Controllers\Admin\SubCriteriaController;
use App\Http\Controllers\Admin\SubCriteriaValueController;

use App\Http\Controllers\User\InternshipVacancyController;
use App\Http\Controllers\User\ResultController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('account', AccountController::class);
    Route::resource('users', UserController::class);
    Route::resource('formulas', FormulaController::class);
    Route::resource('internships', InternshipController::class);
    Route::resource('internships.results', AdminResultController::class);
    Route::post('internships/{internship}/results', [AdminResultController::class, 'changeStatus'])->name('internships.results.changeStatus');
    Route::post('internships/{internship}/announce', [AdminResultController::class, 'announce'])->name('internships.results.announce');

    Route::resource('formulas.criterias', CriteriaController::class)->shallow();
    Route::resource('formulas.criteria-values', CriteriaValueController::class)->shallow();
    Route::resource('formulas.criterias.sub-criterias', SubCriteriaController::class)->shallow();
    Route::resource('formulas.criterias.sub-criteria-values', SubCriteriaValueController::class)->shallow();
    Route::resource('alternatives', AlternativeController::class);
    Route::resource('alternative-values', AlternativeValueController::class);

    Route::get('internship-vacancies/{internshipVacancy}/register', [InternshipVacancyController::class, 'registerForm'])->name('internship-vacancies.register');
    Route::post('internship-vacancies/{internshipVacancy}/register', [InternshipVacancyController::class, 'register'])->name('internship-vacancies.register.store');
    Route::resource('internship-vacancies', InternshipVacancyController::class);
    Route::resource('results', ResultController::class);
});

app/Models/Criteria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Criteria extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'name',
        'formula_id',
        'created_at',
        'updated_at'
    ];

    public function formula()
    {
        return $this->belongsTo('App\Models\Formula', 'formula_id', 'id');
    }

    public function subCriterias()
    {
        return $this->hasMany('App\Models\SubCriteria', 'criteria_id', 'id');
    }
}

app/Http/Controllers/Admin/CriteriaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Criteria;
use App\Models\Formula;
use Illuminate\Http\Request;

class CriteriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $formula)
    {
        $data = Criteria::where('formula_id', $formula)->get();

        return view('admin.criteria.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Formula $formula)
    {
        return view('admin.criteria.create', compact('formula'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Formula $formula)
    {
        $input = $request->validate([
            'name' => 'required|string|max:50'
        ]);

        $formula->criterias()->create($input);

        return redirect()->route('formulas.criterias.index', $formula->id)->with('success', 'Berhasil menambah data kriteria formula '.$formula->name);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Criteria  $criteria
     * @return \Illuminate\Http\Response
     */
    public function show(Criteria $criteria)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Criteria  $criteria
     * @return \Illuminate\Http\Response
     */
    public function edit(Criteria $criteria)
    {
        return view('admin.criteria.edit', compact('criteria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Criteria  $criteria
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Criteria $criteria)
    {
        $input = $request->validate([
            'name' => 'required|string|max:50'
        ]);

        $criteria->update($input);

        return redirect()->route('formulas.criterias.index', $criteria->formula_id)->with('success', 'Berhasil mengubah data kriteria');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Criteria  $criteria
     * @return \Illuminate\Http\Response
     */
    public function destroy(Criteria $criteria)
    {
        $criteria->delete();

        return redirect()->back()->with('success', 'Berhasil menghapus data kriteria');
    }
}

resources/views/admin/criteria/create.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">TAMBAH KRITERIA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Kriteria</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('formulas.criterias.store', $formula->id) }}">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Formula</label>
                        <input type="text" class="form-control" value="{{ $formula->name }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Kriteria</label>
                        <input type="text" class="form-control" name="name" placeholder="Masukkan nama kriteria">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@endsection

resources/views/admin/criteria/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">EDIT KRITERIA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Kriteria / Edit</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('criterias.update', $criteria->id) }}">
                @csrf
                @method('PATCH')
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Formula</label>
                        <input type="text" class="form-control" value="{{ $criteria->formula->name }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Kriteria</label>
                        <input type="text" class="form-control" name="name" value="{{$criteria->name}}" id="exampleInputPassword1" placeholder="nama">
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Ubah</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@endsection

resources/views/admin/criteria/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">KRITERIA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Kriteria</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                    <th width="40">NO</th>
                    <th>NAMA</th>
                    <th width="400">AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data as $krit)
                    <tr>
                        <td class="text-center">{{ $loop->iteration }}</td>
                        <td>{{ $krit->name }}</td>
                        <td class="text-center">
                            <a href="{{ route('formulas.criterias.sub-criterias.index', ['formula' => Request::route('formula'), 'criteria' => $krit->id]) }}">
                                <button class="btn btn-secondary">Daftar Sub Kriteria</button>
                            </a>
                            <a href="{{ route('formulas.criterias.sub-criteria-values.index', ['formula' => Request::route('formula'), 'criteria' => $krit->id]) }}">
                                <button class="btn btn-info">Bobot Sub Kriteria</button>
                            </a>
                            <a href="{{ route('criterias.edit', $krit->id) }}">
                            <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil"></i></button>
                            </a>
                            <form id="delete-kriteria-{{ $krit->id }}" action="{{ route('criterias.destroy', $krit->id) }}" method="post" style="display: inline;">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    $("#data-admin_length").append('<a  href="{{ route('formulas.criterias.create', Request::route('formula')) }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
});
</script>
@endsection