routes/web.php
<?php
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\AccountController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\InternshipController;
use App\Http\Controllers\Admin\ResultController as AdminResultController;
use App\Http\Controllers\Admin\FormulaController;
use App\Http\Controllers\Admin\AlternativeController;
use App\Http\Controllers\Admin\CriteriaController;
use App\Http\Controllers\Admin\CriteriaValueController;
use App\Http\Controllers\Admin\SubCriteriaController;
use App\Http\Controllers\Admin\SubCriteriaValueController;

use App\Http\Controllers\User\InternshipVacancyController;
use App\Http\Controllers\User\ResultController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('account', AccountController::class);
    Route::resource('users', UserController::class);
    Route::resource('formulas', FormulaController::class);
    Route::resource('internships', InternshipController::class);
    Route::resource('internships.results', AdminResultController::class);
    Route::post('internships/{internship}/results', [AdminResultController::class, 'changeStatus'])->name('internships.results.changeStatus');
    Route::post('internships/{internship}/announce', [AdminResultController::class, 'announce'])->name('internships.results.announce');

    Route::resource('formulas.criterias', CriteriaController::class)->shallow();
    Route::resource('formulas.criteria-values', CriteriaValueController::class)->shallow();
    Route::resource('formulas.criterias.sub-criterias', SubCriteriaController::class)->shallow();
    Route::resource('formulas.criterias.sub-criteria-values', SubCriteriaValueController::class)->shallow();
    Route::resource('alternatives', AlternativeController::class);
    Route::resource('alternative-values', AlternativeValueController::class);

    Route::get('internship-vacancies/{internshipVacancy}/register', [InternshipVacancyController::class, 'registerForm'])->name('internship-vacancies.register');
    Route::post('internship-vacancies/{internshipVacancy}/register', [InternshipVacancyController::class, 'register'])->name('internship-vacancies.register.store');
    Route::resource('internship-vacancies', InternshipVacancyController::class);
    Route::resource('results', ResultController::class);
});

resources/views/includes/flash.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success" role="alert">{{$message }}</div>
@endif

@if ($message = Session::get('danger'))
<div class="alert alert-danger">{{$message }}</div>
@endif

@if ($message = Session::get('warning'))
<div class="alert alert-warning">{{$message }}</div>
@endif

@if ($message = Session::get('info'))
<div class="alert alert-info">{{$message }}</div>
@endif

@if ($errors->any())
<div class="alert alert-danger">
    @foreach ($errors->all() as $error)
        <ul>
            <li>{{ $error }}</li>
        </ul>
    @endforeach
</div>
@endif

resources/views/includes/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
        </div>
    </div>
</footer>

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    {{ config('app.name') }}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
                <img class="img-profile rounded-circle"
                    src="img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{ route('account.index') }}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Akun
                </a>
                <div class="dropdown-divider"></div>
                <form id="logout-form" action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button class="dropdown-item" href="#">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </button>
                </form>
            </div>
        </li>

    </ul>

</nav>

resources/views/includes/script.blade.php
<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.js') }}"></script>
<script>
  $(function () {
    $("#data-admin").DataTable();
    $("#data-admin-1").DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "language": {
          "sEmptyTable":   "Tidak ada data yang tersedia pada tabel ini",
    "sProcessing":   "Sedang memproses...",
    "sLengthMenu":   "Tampilkan _MENU_ entri",
    "sZeroRecords":  "Tidak ditemukan data yang sesuai",
    "sInfo":         "Menampilkan _START_ sampai _END_ dari _TOTAL_ entri",
    "sInfoEmpty":    "Menampilkan 0 sampai 0 dari 0 entri",
    "sInfoFiltered": "(disaring dari _MAX_ entri keseluruhan)",
    "sInfoPostFix":  "",
    "sSearch":       "Cari:",
    "sUrl":          "",
    "oPaginate": {
        "sFirst":    "Pertama",
        "sPrevious": "Sebelumnya",
        "sNext":     "Selanjutnya",
        "sLast":     "Terakhir"
    }
        }
    });
  });
</script>

resources/views/includes/sidebar.blade.php
<ul class="navbar-nav bg-gradient-info sidebar sidebar-dark accordion" id="accordionSidebar">

    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SPK <sup>MAGANG</sup></div>
    </a>

    <hr class="sidebar-divider">

    @if(auth()->user()->role == 'admin')
    <div class="sidebar-heading">
        Master Data
    </div>

    <li class="nav-item {{ Request::is('users') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('users.index') }}">
            <i class="fa fa-user"></i>
            <span>USER</span>
        </a>
    </li>

    <li class="nav-item {{ Request::is('internships') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('internships.index') }}">
            <i class="fa fa-list"></i>
            <span>MAGANG</span>
        </a>
    </li>

    <hr class="sidebar-divider">

    <div class="sidebar-heading">
        Perumusan
    </div>

    <li class="nav-item {{ Request::is('formulas*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('formulas.index') }}">
            <i class="fa fa-balance-scale"></i>
            <span>FORMULA</span>
        </a>
    </li>

    @else
    <li class="nav-item {{ Request::is('internship-vacancies') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('internship-vacancies.index') }}">
            <i class="fa fa-list"></i>
            <span>LOWONGAN MAGANG</span>
        </a>
    </li>
    <li class="nav-item {{ Request::is('results') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('results.index') }}">
            <i class="fa fa-bullhorn"></i>
            <span>PENGUMUMAN HASIL</span>
        </a>
    </li>
    @endif

    <hr class="sidebar-divider d-none d-md-block">

    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>