routes/web.php
<?php
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\AccountController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\InternshipController;
use App\Http\Controllers\Admin\ResultController as AdminResultController;
use App\Http\Controllers\Admin\FormulaController;
use App\Http\Controllers\Admin\AlternativeController;
use App\Http\Controllers\Admin\CriteriaController;
use App\Http\Controllers\Admin\CriteriaValueController;
use App\Http\Controllers\Admin\SubCriteriaController;
use App\Http\Controllers\Admin\SubCriteriaValueController;

use App\Http\Controllers\User\InternshipVacancyController;
use App\Http\Controllers\User\ResultController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('account', AccountController::class);
    Route::resource('users', UserController::class);
    Route::resource('formulas', FormulaController::class);
    Route::resource('internships', InternshipController::class);
    Route::resource('internships.results', AdminResultController::class);
    Route::post('internships/{internship}/results', [AdminResultController::class, 'changeStatus'])->name('internships.results.changeStatus');
    Route::post('internships/{internship}/announce', [AdminResultController::class, 'announce'])->name('internships.results.announce');

    Route::resource('formulas.criterias', CriteriaController::class)->shallow();
    Route::resource('formulas.criteria-values', CriteriaValueController::class)->shallow();
    Route::resource('formulas.criterias.sub-criterias', SubCriteriaController::class)->shallow();
    Route::resource('formulas.criterias.sub-criteria-values', SubCriteriaValueController::class)->shallow();
    Route::resource('alternatives', AlternativeController::class);
    Route::resource('alternative-values', AlternativeValueController::class);

    Route::get('internship-vacancies/{internshipVacancy}/register', [InternshipVacancyController::class, 'registerForm'])->name('internship-vacancies.register');
    Route::post('internship-vacancies/{internshipVacancy}/register', [InternshipVacancyController::class, 'register'])->name('internship-vacancies.register.store');
    Route::resource('internship-vacancies', InternshipVacancyController::class);
    Route::resource('results', ResultController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::where('role', 'user')->get();

        return view('admin.user.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        try {
            $user->delete();
        } catch (\Throwable $th) {
            return redirect()->back()->with('danger', 'Gagal menghapus User');
        }

        return redirect()->back()->with('success', 'Berhasil menghapus User');
    }
}

app/Http/Controllers/User/InternshipVacancyController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Internship;
use App\Models\Criteria;
use App\Models\Alternative;
use Illuminate\Http\Request;

class InternshipVacancyController extends Controller
{
    public function index()
    {
        $data = Internship::withCount('registrants', 'hasRegister')->latest()
            ->whereNotNull('start_at')
            ->whereNull('end_at')
            ->get();

        return view('user.internship.index', compact('data'));
    }
    
    public function show(Internship $internshipVacancy)
    {
        return view('user.internship.show', compact('internshipVacancy'));
    }
    
    public function registerForm(Internship $internshipVacancy)
    {
        $internshipVacancy = $internshipVacancy->load('formula.criterias.subCriterias');
        return view('user.internship.register', compact('internshipVacancy'));
    }
    
    public function register(Request $request, Internship $internshipVacancy)
    {
        $alternative = Alternative::firstOrCreate([
            'user_id' => auth()->user()->id,
            'internship_id' => $internshipVacancy->id],[
            'status' => 'DAFTAR'
        ]);
        foreach ($request->value as $key => $value) {
            $alternative->alternativeValues()->create([
                'criteria_id' => $key,
                'sub_criteria_id' => $value
            ]);
        }

        return redirect()->route('results.index')->with('success',
        'Berhasil melamar magang');
    }

    public function result()
    {
        $data = Alternative::with('user', 'internship')
            ->where('user_id', auth()->user()->id)
            ->get();

        return view('user.internship.result.index', compact('data'));
    }

}

app/Http/Controllers/User/ResultController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Internship;
use App\Models\Alternative;
use Illuminate\Http\Request;

class ResultController extends Controller
{
    public function index()
    {
        $data = Alternative::with('user', 'internship')
            ->where('user_id', auth()->user()->id)
            ->get();

        return view('user.internship.result.index', compact('data'));
    }
    public function show($id)
    {
        $data = Internship::with('registrants.user')
            ->whereHas('registrants', function($q){
                $q->where('user_id', auth()->user()->id);
            })
            ->where('id', $id)
            ->firstOrFail();

        if(!$data->announce_at){
            abort(403);
        }

        return view('user.internship.result.show', compact('data'));
    }
}

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h2 class="m-0 text-dark">USER</h2>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">User</li>
            </ol>
        </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="10">NO</th>
                        <th>NAMA</th>
                        <th>EMAIL</th>
                        <th width="70">AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data as $sis)
                    <tr>
                        <td class="text-center">{{$loop->iteration}}</td>
                        <td>{{$sis->name}}</td>
                        <td>{{$sis->email}}</td>
                        <td class="text-center">
                            {{-- <a href="{{ route('users.edit', $sis->id) }}">
                                <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil"></i></button>
                            </a> --}}
                            <form id="delete-siseria-{{$sis->id}}" action="{{ route('users.destroy', $sis->id) }}" method="post" style="display: inline;">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</section>
@include ('includes.script')
@endsection